# From https://github.com/hatena/renovate-config/edit/master/.github/workflows/validate-config.yml

name: Validate renovate config

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CI: true

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node
    - name: Validate renovate config
      run: ./.check.sh
